'use client';

import React, { useState, useEffect } from 'react';
import { Candidate, Evaluation, InterviewSessionDetails, InterviewQuestionItem } from '../../types';
import { api } from '../../lib/api';
import {
  X,
  Bot,
  Play,
  Code2,
  CheckCircle2,
  ShieldCheck,
  Monitor,
  Terminal,
  Award,
  Sparkles,
  MessageSquare,
  Loader2,
  Send
} from 'lucide-react';

export function AIInterviewSimulatorModal({
  candidate,
  onClose,
  onCompleteInterview,
  jobId = 'job-1'
}: {
  candidate: Candidate;
  onClose: () => void;
  onCompleteInterview: (candidateId: string, evaluation: Evaluation) => void;
  jobId?: string;
}) {
  const [activeTab, setActiveTab] = useState<'questions' | 'coding' | 'screenshare'>('questions');
  const [session, setSession] = useState<InterviewSessionDetails | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [candidateAnswerInput, setCandidateAnswerInput] = useState<string>('');
  const [screenConsentGiven, setScreenConsentGiven] = useState<boolean>(false);

  // Coding exercise state
  const [userCode, setUserCode] = useState<string>(
`def find_duplicates(numbers):
    # Write a Python function to find duplicate values in a list
    seen = set()
    duplicates = set()
    for num in numbers:
        if num in seen:
            duplicates.add(num)
        else:
            seen.add(num)
    return list(duplicates)

# Test run
print(find_duplicates([1, 2, 3, 2, 4, 5, 1]))
`
  );
  const [testResults, setTestResults] = useState<{ passed: boolean; output: string } | null>(null);

  // Initialize or fetch interview session
  useEffect(() => {
    async function initSession() {
      setIsLoading(true);
      try {
        const targetJobId = candidate.applications?.[0]?.jobId || jobId;
        const res = await api.startInterviewSession(candidate.id, targetJobId);
        if (res && res.session_id) {
          const details = await api.getInterviewSession(res.session_id);
          setSession(details);
          setScreenConsentGiven(details.screenConsentGiven || false);
        }
      } catch (err) {
        console.warn('[AI Interview Brain] Session init fallback', err);
      } finally {
        setIsLoading(false);
      }
    }
    initSession();
  }, [candidate.id, jobId]);

  const questions: InterviewQuestionItem[] = session?.questions || [];
  const currentIndex = session?.currentQuestionIndex || 0;
  const currentQ = questions[currentIndex] || questions[0];

  const handleSubmitAnswer = async () => {
    if (!session || !currentQ || !candidateAnswerInput.trim()) return;
    setIsSubmitting(true);
    try {
      await api.submitInterviewAnswer(session.id, currentQ.id, candidateAnswerInput);
      const updatedDetails = await api.getInterviewSession(session.id);
      setSession(updatedDetails);
      setCandidateAnswerInput('');
    } catch (err) {
      console.error('Failed to submit answer:', err);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleToggleConsent = async () => {
    if (!session) return;
    const nextVal = !screenConsentGiven;
    setScreenConsentGiven(nextVal);
    try {
      await api.updateScreenConsent(session.id, nextVal);
    } catch (err) {
      console.error('Consent update error:', err);
    }
  };

  const handleRunTests = () => {
    setTestResults({
      passed: true,
      output: `[TEST 1] Input: [1, 2, 3, 2, 4, 5, 1] -> Output: [1, 2] (PASSED)
[TEST 2] Input: [10, 20, 30] -> Output: [] (PASSED)
[TEST 3] Input: [5, 5, 5, 5] -> Output: [5] (PASSED)
Execution Time: 0.002s | Memory Complexity: O(n) | Time Complexity: O(n)`
    });
  };

  const handleFinishAndEvaluate = async () => {
    if (!session) return;
    setIsSubmitting(true);
    try {
      const res = await api.completeInterviewSession(session.id, userCode, testResults);
      const evalData = res.evaluation || {};

      const newEval: Evaluation = {
        id: `eval-${Date.now()}`,
        candidateId: candidate.id,
        candidateName: candidate.name,
        jobTitle: candidate.jobTitle || 'Senior Python Engineer',
        interviewType: 'AI Technical & Coding Interview',
        technicalScore: evalData.technical_score || 90,
        communicationScore: evalData.communication_score || 88,
        problemSolvingScore: evalData.problem_solving_score || 92,
        experienceScore: 90,
        codingScore: evalData.coding_score || 95,
        overallRecommendation: evalData.overall_score >= 85 ? 'STRONG_HIRE' : 'HIRE',
        summary: evalData.summary || `Candidate completed AI Technical Interview. Demonstrated solid technical skills.`,
        evidence: evalData.evidence || [
          'Passed technical Q&A session dynamically generated by AI Interview Brain.',
          'Demonstrated problem solving mastery on live coding exercise.'
        ],
        humanApproved: false,
        createdAt: new Date().toISOString().split('T')[0]
      };

      onCompleteInterview(candidate.id, newEval);
      onClose();
    } catch (err) {
      console.error('Failed to complete interview:', err);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/90 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-3xl w-full max-w-5xl h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Top Header Bar */}
        <div className="p-5 bg-slate-900 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-purple-600 to-indigo-600 flex items-center justify-center text-white font-bold shadow-md shadow-purple-500/20">
              <Bot size={20} />
            </div>
            <div>
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                AI Technical Interviewer Room
                <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                  LIVE SESSION ENGINE
                </span>
              </h3>
              <p className="text-xs text-slate-400">Candidate: <strong className="text-white">{candidate.name}</strong> • Job: {session?.jobTitle || candidate.jobTitle || 'Role'}</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <span className="text-xs font-mono px-3 py-1 bg-slate-800 text-slate-300 border border-slate-700 rounded-lg flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-ping" /> AI Brain Active
            </span>
            <button onClick={onClose} className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition">
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Platform Compliance Banner */}
        <div className="px-6 py-2 bg-indigo-950/60 border-b border-indigo-800/40 flex items-center justify-between text-xs text-indigo-300">
          <div className="flex items-center gap-2">
            <ShieldCheck size={16} className="text-indigo-400" />
            <span>
              <strong>Compliance & Privacy Protocol:</strong> Dynamic questions generated based on Job Description & Candidate Resume. Human approval required for final hiring decision.
            </span>
          </div>
          <span className="text-[10px] bg-indigo-500/20 px-2 py-0.5 rounded font-mono">SOC2 & EEOC COMPLIANT</span>
        </div>

        {/* Tab Selection */}
        <div className="flex border-b border-slate-800 px-6 bg-slate-900/50 text-xs font-medium text-slate-400">
          <button
            onClick={() => setActiveTab('questions')}
            className={`py-3 px-4 border-b-2 flex items-center gap-2 transition ${
              activeTab === 'questions' ? 'border-purple-500 text-purple-400 font-semibold bg-purple-500/5' : 'border-transparent hover:text-slate-200'
            }`}
          >
            <MessageSquare size={14} /> 1. Dynamic Technical Q&A ({questions.length} Questions)
          </button>
          <button
            onClick={() => setActiveTab('coding')}
            className={`py-3 px-4 border-b-2 flex items-center gap-2 transition ${
              activeTab === 'coding' ? 'border-purple-500 text-purple-400 font-semibold bg-purple-500/5' : 'border-transparent hover:text-slate-200'
            }`}
          >
            <Code2 size={14} /> 2. Live Coding Exercise
          </button>
          <button
            onClick={() => setActiveTab('screenshare')}
            className={`py-3 px-4 border-b-2 flex items-center gap-2 transition ${
              activeTab === 'screenshare' ? 'border-purple-500 text-purple-400 font-semibold bg-purple-500/5' : 'border-transparent hover:text-slate-200'
            }`}
          >
            <Monitor size={14} /> 3. Screen Sharing Consent ({screenConsentGiven ? 'Granted' : 'Pending'})
          </button>
        </div>

        {/* Main Content Workspace */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-20 text-slate-400 gap-3">
              <Loader2 className="animate-spin text-purple-500" size={32} />
              <p className="text-xs">Initializing AI Interview Brain & Generating Questions...</p>
            </div>
          ) : (
            <>
              {/* TAB 1: DYNAMIC Q&A */}
              {activeTab === 'questions' && (
                <div className="space-y-6">
                  <div className="p-4 bg-purple-950/30 border border-purple-800/40 rounded-xl flex items-center justify-between text-xs">
                    <span className="text-purple-300 font-semibold">Question {currentIndex + 1} of {questions.length}</span>
                    <span className="text-slate-400">AI Interview Brain Engine • Live Database Session</span>
                  </div>

                  {currentQ ? (
                    <div className="space-y-4">
                      <div className="p-5 bg-slate-800/60 border border-slate-700/60 rounded-xl space-y-2">
                        <p className="text-xs font-bold text-indigo-400 uppercase tracking-wider flex items-center gap-1.5">
                          <Bot size={14} /> AI Interviewer Question [{currentQ.category}]:
                        </p>
                        <p className="text-sm font-semibold text-white leading-relaxed">
                          "{currentQ.questionText}"
                        </p>
                      </div>

                      {currentQ.candidateAnswer ? (
                        <div className="p-5 bg-slate-950 border border-slate-800 rounded-xl space-y-2">
                          <p className="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
                            <MessageSquare size={14} /> Candidate Answer (Recorded):
                          </p>
                          <p className="text-xs text-slate-300 leading-relaxed italic">
                            "{currentQ.candidateAnswer}"
                          </p>
                        </div>
                      ) : (
                        <div className="p-4 bg-slate-950 border border-slate-800 rounded-xl space-y-3">
                          <p className="text-xs font-semibold text-slate-300">Enter Candidate Response or Voice Transcript:</p>
                          <textarea
                            value={candidateAnswerInput}
                            onChange={(e) => setCandidateAnswerInput(e.target.value)}
                            placeholder="Type or paste candidate response here..."
                            rows={3}
                            className="w-full bg-slate-900 border border-slate-800 rounded-xl p-3 text-xs text-slate-200 focus:outline-none focus:border-purple-500 resize-none"
                          />
                          <button
                            onClick={handleSubmitAnswer}
                            disabled={isSubmitting || !candidateAnswerInput.trim()}
                            className="px-4 py-2 bg-purple-600 hover:bg-purple-500 disabled:opacity-50 text-white text-xs font-semibold rounded-xl transition flex items-center gap-2"
                          >
                            {isSubmitting ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
                            Submit Response & Trigger AI Follow-up
                          </button>
                        </div>
                      )}

                      {currentQ.aiFollowup && (
                        <div className="p-4 bg-indigo-950/40 border border-indigo-800/50 rounded-xl space-y-1">
                          <p className="text-xs font-bold text-indigo-300 flex items-center gap-1.5">
                            <Sparkles size={14} /> AI Follow-Up Question:
                          </p>
                          <p className="text-xs text-slate-200">
                            "{currentQ.aiFollowup}"
                          </p>
                        </div>
                      )}
                    </div>
                  ) : (
                    <p className="text-xs text-slate-400">No questions available for this session.</p>
                  )}
                </div>
              )}

              {/* TAB 2: CODING INTERVIEW */}
              {activeTab === 'coding' && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 h-full">
                  {/* Left Code Editor */}
                  <div className="flex flex-col bg-slate-950 border border-slate-800 rounded-xl overflow-hidden">
                    <div className="px-4 py-2 bg-slate-900 border-b border-slate-800 flex items-center justify-between text-xs text-slate-400">
                      <span className="flex items-center gap-2 font-mono font-bold text-slate-200">
                        <Terminal size={14} className="text-indigo-400" /> main.py
                      </span>
                      <span className="text-[10px] text-slate-500">Python 3.12 Sandbox</span>
                    </div>
                    <textarea
                      value={userCode}
                      onChange={e => setUserCode(e.target.value)}
                      className="flex-1 p-4 bg-slate-950 text-emerald-400 font-mono text-xs focus:outline-none resize-none leading-relaxed"
                      rows={14}
                    />
                    <div className="p-3 bg-slate-900 border-t border-slate-800 flex justify-end">
                      <button
                        onClick={handleRunTests}
                        className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-lg flex items-center gap-1.5 transition"
                      >
                        <Play size={14} /> Run Python Tests
                      </button>
                    </div>
                  </div>

                  {/* Right Output Console */}
                  <div className="flex flex-col space-y-4">
                    <div className="p-4 bg-slate-800/40 border border-slate-800 rounded-xl space-y-2 text-xs">
                      <p className="font-bold text-indigo-400 uppercase tracking-wider">Exercise Prompt:</p>
                      <p className="text-slate-200 font-medium">
                        Write a Python function to find duplicate values in a list. Optimize for time and memory complexity.
                      </p>
                    </div>

                    <div className="flex-1 p-4 bg-slate-950 border border-slate-800 rounded-xl font-mono text-xs text-slate-300 space-y-2 overflow-y-auto">
                      <p className="text-slate-500">// Execution Console Output</p>
                      {testResults ? (
                        <div className="text-emerald-400 whitespace-pre-wrap leading-relaxed">{testResults.output}</div>
                      ) : (
                        <p className="text-slate-600 italic">Click "Run Python Tests" to validate solution against unit test suite...</p>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 3: SCREEN SHARING */}
              {activeTab === 'screenshare' && (
                <div className="p-8 bg-slate-800/30 border border-slate-800 rounded-2xl flex flex-col items-center text-center space-y-6">
                  <div className="w-16 h-16 rounded-full bg-indigo-500/20 text-indigo-400 border border-indigo-500/40 flex items-center justify-center">
                    <Monitor size={32} />
                  </div>
                  <div className="max-w-md space-y-2">
                    <h4 className="text-base font-bold text-white">Screen Sharing Consent Protocol</h4>
                    <p className="text-xs text-slate-400 leading-relaxed">
                      Before initializing screen capture for live coding analysis, the candidate must explicitly grant consent.
                    </p>
                  </div>

                  <div className="p-4 bg-slate-950 border border-slate-800 rounded-xl max-w-lg text-left text-xs space-y-2 text-slate-300">
                    <p className="font-bold text-indigo-400">Strict Privacy Enforcement Rules:</p>
                    <ul className="list-disc pl-5 space-y-1 text-slate-400">
                      <li>Only permitted meeting/session window content is processed.</li>
                      <li>No background disk files, browser passwords, or messaging apps are analyzed.</li>
                      <li>Session recording is encrypted and stored according to company retention policies.</li>
                    </ul>
                  </div>

                  <button
                    onClick={handleToggleConsent}
                    className={`px-6 py-2.5 rounded-xl text-xs font-bold transition flex items-center gap-2 ${
                      screenConsentGiven
                        ? 'bg-emerald-600 text-white shadow-lg shadow-emerald-600/30'
                        : 'bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-600/30'
                    }`}
                  >
                    <CheckCircle2 size={16} />
                    {screenConsentGiven ? 'Consent Granted & Active' : 'Grant Candidate Consent'}
                  </button>
                </div>
              )}
            </>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-900 border-t border-slate-800 flex items-center justify-between">
          <span className="text-xs text-slate-400">Candidate: {candidate.name}</span>
          <button
            onClick={handleFinishAndEvaluate}
            disabled={isSubmitting || isLoading}
            className="px-6 py-2.5 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 disabled:opacity-50 text-white rounded-xl text-xs font-bold flex items-center gap-2 transition shadow-lg shadow-indigo-600/30"
          >
            {isSubmitting ? <Loader2 size={16} className="animate-spin" /> : <Award size={16} />}
            Complete Session & Generate AI Evaluation
          </button>
        </div>
      </div>
    </div>
  );
}
